version: '3.8'

services:
  supabase:
    image: supabase/supabase:latest
    ports:
      - "54321:54321"  # API
      - "54322:54322"  # Database
      - "54323:54323"  # Studio
      - "54324:54324"  # Inbucket (email testing)
    environment:
      - SUPABASE_URL=http://localhost:54321
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    volumes:
      - ./supabase:/app/supabase
    networks:
      - supabase-network

networks:
  supabase-network:
    driver: bridge